[MySQL]
UserName     = "root"
Password     = "lzq"
Addr          = "localhost:3306"
DatabaseName = "summer_project"
[Redis]
    [FollowingList]
        Addr         = "localhost:6379"
        Password     = ""
        DB           = 0
    [FollowersList]
        Addr         = "localhost:6379"
        Password     = ""
        DB           = 1
    [MutualFollowList]
        Addr         = "localhost:6379"
        Password     = ""
        DB           = 2
[WebService]
Addr         = "localhost:8617"
# 以下并未采用配置文件写入
[Default]
Cover = "https://img-blog.csdnimg.cn/img_convert/7ad86d3945ddf7946e39d179e60c5687.png"
Avatar = "https://image-1302243118.cos.ap-beijing.myqcloud.com/public/img/BLUE_GLASSES_GOPHER-1616727843503.png"